# Generated by Django 4.0.3 on 2022-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_image_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_pic',
        ),
    ]
