# Generated by Django 4.0.3 on 2022-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_image_image_image_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_pic',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Image', upload_to='images/'),
        ),
    ]
