# Generated by Django 4.0.3 on 2022-04-01 17:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_remove_image_image_pic_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(default='No Comment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
    ]
