# Generated by Django 4.0.3 on 2022-04-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_rename_img_caption_image_image_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
